openapi: "3.1.0"
info:
  title: Relative Resolver Failure
  version: 2.0.0
paths:
  /v1.0/endpoint:
    get:
      description: Relative Resolver Failure
      parameters:
        - in: query
          name: param
          required: true
          description: param for testing
          schema:
            type: string
          examples:
            EXAMPLE1:
              value: 1
            
            

      responses:
        '200':

          content:
            application/json:
              examples:
                $ref: ./hop1.yaml

          description: Broken Ref Resolver

